spring:
  main:
    sources: camelinaction.OrderRoute
  datasource:
      url: jdbc:postgresql://postgres/fooBarBaz
      username: fooBarBaz
      password: fooBarBaz
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
